baseURL = 'https://spicecat2.github.io/w-b-yeats/'
defaultContentLanguage = 'en'
enableEmoji = true
languageCode = 'en-us'
paginate = 10
theme = 'pico'
title = 'W. B. Yeats'

[params]
customCSS = [
	"style/style.css",
	"style/theme.sass",
]
customJS = ["js/console.js"]

description = "William Butler Yeats website"
favicon = '/favicon.ico'

[menu]

[[menu.main]]
identifier = "home"
pre = ""
url = "/" 
weight = 10 

[[menu.main]]
identifier = "blog"
pre = ""
url = "/blog/" 
weight = 20 

[markup.highlight]
guessSyntax = true 
lineNumbersInTable = true 
noClasses = false
tabWidth = 2 

[taxonomies]
category = "categories"
tag = "tags"

[languages.en]
contentDir = 'content/en'
languageCode = 'en'
languageName = 'English'
weight = 0

[permalinks]
blog = 'works/:filename'